### ISSUE TITLE
Recommendation: require RandomLib if you use it as a fallback

### ISSUE THREAD

**Issue by Saeven** [zendframework/zend-math#17]
Ran into this: https://github.com/zendframework/zend-math/blob/master/src/Rand.php#L75

I think userland (at least me) would rather have composer install this rather than run into this message.

**Comment by johnnymallie** [comment]
Hi ! I had the same problem this morning after a composer update.

I agree with Saeven, even tough I'm not sure if it's the best fit.

Looking forward for a solution or a guideline to follow

**Comment by ezimuel** [comment]
@Saeven we put this message to alert about the need of [ircmaxell/random-lib](https://github.com/ircmaxell/RandomLib) if Mcrypt is not installed. We removed the usage of OpenSSL for security reason, see [ZF2016-01](http://framework.zend.com/security/advisory/ZF2016-01).
You can easily fix it adding the library in composer, using the following command:

```
composer require ircmaxell/random-lib:1.*
```

In composer.json we added this [suggestion](https://github.com/zendframework/zend-math/blob/master/composer.json#L21) long time ago.

**Comment by Saeven** [comment]
Hi Ezimuel

I understand.  This is a case where it is such a small download, that requiring the lib would be more beneficial to users than investigating a solution.  Those recommendations don't come through on updates, so when I last composer updated, all you get is a break.  I realize this is a temporal thing.

On the subject, I would submit that mcrypt is dinosaurware, and is on its way out (https://wiki.php.net/rfc/mcrypt-viking-funeral).  Its last release was in 2007 (8 years and some change).  I think users are acknowledging this and are opting for things like defuse, libsodium, and openssl (in no particular order). 

I would table the recommendation that openssl_random_pseudo_bytes precede RandomLib if you aren't of the mindset to require it (it'd still be a nice gesture!).  

```
if random bytes
else if openssl random pbytes
else if mcrypt //ugh
else RandomLib or burn
```

Cheers.
Alex

**Comment by ezimuel** [comment]
Hi Alexander,

we did this change because openssl_random_pseudo_bytes() is affected by PHP
bug #70014 (https://bugs.php.net/bug.php?id=70014) and also because of the
issues reported in this discussion:
https://github.com/paragonie/random_compat/issues/96.
The usage of mcrypt in zend-math is only for the pseudo random number
generation. We know that mcrypt is outdated but this is the only
alternative that we have here.
Anyway, we will release a new pseudo random generator for ZF3 based on PHP
7 functions and https://github.com/paragonie/random_compat usage for PHP 5.x

2016-04-19 15:00 GMT+02:00 Alexandre Lemaire <notifications@github.com>:
